### ISSUE TITLE
Support mobile devices using PhoneGap/Cordova

### ISSUE THREAD

**Issue by tomchiverton** [emailjs/emailjs-tcp-socket#28]
I think this would require a new shim to support https://github.com/blocshop/sockets-for-cordova probably also using Forge to provide TLS like the existing one does

**Comment by RedHatter** [comment]
Emailjs works great on Cordova using the [cordova-plugin-chrome-apps-sockets-tcp](https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-sockets-tcp) plugin. The plugin you listed is actually much slower and more error prone.

**Comment by nifgraup** [comment]
Closing, no action needed.
