### ISSUE TITLE
State of Cordova support; Why are we still using forge?

### ISSUE THREAD

**Issue by RedHatter** [emailjs/emailjs-tcp-socket#34]
I'm using emailjs on Cordova using the [cordova-plugin-chrome-apps-sockets-tcp](https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-sockets-tcp) plugin. By default emailjs is still using forge with Cordova, but after editing the code below to use native TLS everything still works great. Is the fix no longer needed?

    chrome.runtime.getPlatformInfo(function(platformInfo) {

        //
        // FIX START
        //

        if (platformInfo.os.indexOf("cordova") !== -1) {
            // chrome.sockets.tcp.secure is not functional on cordova
            // https://github.com/MobileChromeApps/mobile-chrome-apps/issues/269
            self._useLegacySocket = false;
            self._useForgeTls = false;
        } else {
            self._useLegacySocket = true;
            self._useForgeTls = false;
        }

        //
        // FIX END
        //

        // fire up the socket
        if (self._useLegacySocket) {
            self._createLegacySocket();
        } else {
            self._createSocket();
        }
    });

**Comment by nifgraup** [comment]
Did you connect with STARTTLS as well? This pull request https://github.com/emailjs/emailjs-tcp-socket/pull/27 fixed STARTTLS in Desktop Chrome Apps, did it also fix Cordova?

**Comment by felixhammerl** [comment]
I'm going to close this as chrome apps are going away and support for chrome apps will be removed going forward.

see: https://github.com/emailjs/emailjs-imap-client/issues/158
